# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Anvil_config = debug
endif
ifeq ($(config),release)
  Anvil_config = release
endif

PROJECTS := Anvil

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Anvil:
ifneq (,$(Anvil_config))
	@echo "==== Building Anvil ($(Anvil_config)) ===="
	@${MAKE} --no-print-directory -C Anvil -f Makefile config=$(Anvil_config)
endif

clean:
	@${MAKE} --no-print-directory -C Anvil -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Anvil"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"