#include "Keys.h"
#include <GLFW/glfw3.h>

enum Keys
{
	ANV_KEY_A = GLFW_KEY_A,
	ANV_KEY_B = GLFW_KEY_B,
	ANV_KEY_C = GLFW_KEY_C,
	ANV_KEY_D = GLFW_KEY_D,
	ANV_KEY_E = GLFW_KEY_E,
	ANV_KEY_F = GLFW_KEY_F,
	ANV_KEY_G = GLFW_KEY_G,
	ANV_KEY_H = GLFW_KEY_H,
	ANV_KEY_I = GLFW_KEY_I,
	ANV_KEY_J = GLFW_KEY_J,
	ANV_KEY_K = GLFW_KEY_K,
	ANV_KEY_L = GLFW_KEY_L,
	ANV_KEY_M = GLFW_KEY_M,
	ANV_KEY_N = GLFW_KEY_N,
	ANV_KEY_O = GLFW_KEY_O,
	ANV_KEY_P = GLFW_KEY_P,
	ANV_KEY_Q = GLFW_KEY_Q,
	ANV_KEY_R = GLFW_KEY_R,
	ANV_KEY_S = GLFW_KEY_S,
	ANV_KEY_T = GLFW_KEY_T,
	ANV_KEY_U = GLFW_KEY_U,
	ANV_KEY_V = GLFW_KEY_V,
	ANV_KEY_W = GLFW_KEY_W,
	ANV_KEY_X = GLFW_KEY_X,
	ANV_KEY_Y = GLFW_KEY_Y,
	ANV_KEY_Z = GLFW_KEY_Z,
};